### ISSUE TITLE
Option `-a` is not supported correctly between scaffolding, others command

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-supervisor#27]
Option `-a` is not supported correctly between scaffolding, others command as we can initialise a project 

```
sb init -a demo
```

but we can't next push a binary

**Comment by metacosm** [comment]
For one thing, `init` command should be removed as it is completely unneeded. All commands should automatically perform the init step when needed.
Which sequence of commands is failing more precisely?
```sb init -a demo
sb create
sb push --mode binary```

**Comment by geoand** [comment]
@metacosm The sequence you of commands you provided would fail without this PR (if of course the name of the directory you are working in is **not** demo)

**Comment by geoand** [comment]
I definitely see why removing `init` would be a good things, but I think that we would need to introduce "dependencies" between commands

**Comment by metacosm** [comment]
@geoand not necessarily, we could use the code you just created to check whether we have already initialized the project before any command…

**Comment by geoand** [comment]
True, didn't think of it that way :)
