### ISSUE TITLE
Pass parameters of the service instance to be created

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-supervisor#44]
The project currently hard code the ServiceInstance to be created and doesn't propose a nice approach to pass the parameters about the database's configuration

We should extend the Application Type to include a ServiceInstance Type and Parameters that we could populate from the MANIFEST file

Hard coded data are 

```
const (
	CLASS_NAME                  = "dh-postgresql-apb"
	INSTANCE_NAME				= "my-postgresql-db"
	PLAN                        = "dev"
	EXTERNAL_ID                 = "a7c00676-4398-11e8-842f-0ed5f89f718b"
	POSTGRESQL_VERSION          = "9.6"
	NS                          = "crud"
)
```

and the parameters associated to the DEV's plan are

```
var (
	PARAMS = map[string]string{
		"postgresql_user": "luke",
		"postgresql_password": "secret",
		"postgresql_database": "my_data",
		"postgresql_version": "9.6",
	}
) 
```

Remark : the parameters will change according to the plan and the service !!

**Comment by iocanel** [comment]
How we pass these to the application varies from app to app.
For example an app may access those via env vars, config files or even via spring cloud connectors.

# Envars
only thing that pops to my mind is to wrap the startup script of the app in such a way that would restart the process and set env variables. 

# Config files
we can copy the file to where it needs to be. spring apps can even triger a reload.

# Connectors
This should be taken care by the app.

**Comment by geoand** [comment]
Do we want to propose something general here? I can see `CLASS_NAME`, `INSTANCE_NAME`, `SECRET_NAME`, `BINDING_NAME` and `PLAN` being command line arguments.

I don't see however what I nice way to pass `PARAMS` would be... It could be a comma separated value of strings, but that wouldn't make demos look good.

**Comment by metacosm** [comment]
Best way would be to deal with this interactively, imo.

**Comment by metacosm** [comment]
For that matter, I think that tools should be interactive as much as possible offering completion / validation of input (similar to what Forge does/did)…

**Comment by geoand** [comment]
So what do want to do in the short term (for the demo that is)?

**Comment by geoand** [comment]
Also keep in mind that `INSTANCE_NAME` is needed by both `create` and `bind`

**Comment by metacosm** [comment]
Well, for one thing, the service should use the data that's in the manifest. So the manifest data should be made available to the commands. Will take a stab at it.

**Comment by metacosm** [comment]
Actually, ideally, if service information is in the manifest, the tool should probably call the Service Catalog automatically (at some point). Or do we want to keep that process explicit?

**Comment by geoand** [comment]
I would say at the moment we keep it explicit. But I really do like the idea of moving the config in the MANIFEST
