### ISSUE TITLE
Blocking issue : Pod watch error: unknown error while waiting for pod matching

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-supervisor#52]
Error reported by @bgeorges using 0.7.0

```
sorig:kjbug bgeorges$ sb push --mode binary
INFO[0000] Push command called with mode 'binary'       
INFO[0000] Parse MANIFEST of the project if it exists   
INFO[0000] Application configured                       
INFO[0000] Get K8s config file                          
INFO[0000] Using 'crud-catalog' namespace               
INFO[0000] Create k8s Rest config client using the developer's machine config file 
INFO[0000] Create k8s Clientset                         
INFO[0000] Using application name 'my-spring-boot' that was set in MANIFEST 
INFO[0000] Wait till the dev pod is available           
FATA[0000] Pod watch error: unknown error while waiting for pod matching '{{ } app=my-spring-boot  %!s(bool=false) %!s(bool=false)  %!s(*int64=<nil>) %!s(int64=0) }' selector
```

**Comment by geoand** [comment]
This could happens if `sb init` has not been run before `sb push` was called.

@bgeorges Could you please provide the commands you executed before running `sb push --mode binary`? 
Thanks

**Comment by cmoulliard** [comment]
I can'r reproduce it using minishift 1.23 with origin 3.10 on my macbook

Here is the scenario played : https://gist.github.com/cmoulliard/82cd553fc458753902978e5e6c5f549c

**Comment by cmoulliard** [comment]
@bgeorges  What is label of your application as it seems that the label's selector which is used to fetch the pod is buggy -> `'{{ } app=my-spring-boot  %!s(bool=false) %!s(bool=false)  %!s(*int64=<nil>) %!s(int64=0) }'` ?

**Comment by cmoulliard** [comment]
Fixed with #PR53
